# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Hillside Projects
email:            info@hillsideprojects.se
description:      A portfolio of the research/production group formed by Emily Mennerdahl and Jonas Böttern.
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://hillsideprojects.github.io/' # The base hostname & protocol for your site
facebook_username:  HillsideProjects
vimeo_username: user31098743

markdown:  kramdown
permalink: pretty
paginate:  12

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             Hillside Projects
    bio:              Hillside Projects is a research and production group consisting of artists Emily Mennerdahl and Jonas Böttern. Hillside Projects works interdisciplinary and mainly focuses on the development and changes in the natural world. Always trying to dismantle and re-consider the things, the things as we know them. The things we like to consider facts or even knowledge.
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:            info@hillsideprojects.se
    website:          https://hillsideprojects.se
    github_username:  ahmadajmi
    twitter_username: ahmadajmi
